name: NotchyTeleprompterIOS
options:
  bundleIdPrefix: com.notchy
settings:
  base:
    SWIFT_VERSION: "5.10"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    PRODUCT_BUNDLE_IDENTIFIER: com.notchy.teleprompter.ios
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    TARGETED_DEVICE_FAMILY: "1"
    SUPPORTS_MACCATALYST: NO
targets:
  NotchyTeleprompterIOS:
    type: application
    platform: iOS
    sources:
      - path: NotchyTeleprompterIOS
    settings:
      base:
        INFOPLIST_FILE: NotchyTeleprompterIOS/App/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        PRODUCT_NAME: Notchy Teleprompter iOS
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
schemes:
  NotchyTeleprompterIOS:
    build:
      targets:
        NotchyTeleprompterIOS: all
    run:
      config: Debug
    archive:
      config: Release
