name: NotchyTeleprompter
options:
  bundleIdPrefix: com.notchy
packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.6.4
settings:
  base:
    SWIFT_VERSION: "5.10"
    MACOSX_DEPLOYMENT_TARGET: 11.0
    PRODUCT_BUNDLE_IDENTIFIER: com.notchy.teleprompter.native
    MARKETING_VERSION: 2.2.7
    CURRENT_PROJECT_VERSION: 13
    CODE_SIGN_STYLE: Automatic
targets:
  NotchyTeleprompter:
    type: application
    platform: macOS
    sources:
      - path: NotchyTeleprompter
        excludes:
          - Resources/Fonts/Season/*.ttf
          - Resources/Fonts/Season/Befonts-License.txt
    settings:
      base:
        INFOPLIST_FILE: NotchyTeleprompter/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        PRODUCT_NAME: Notchy Teleprompter
        ENABLE_HARDENED_RUNTIME: YES
        SWIFT_EMIT_LOC_STRINGS: NO
    dependencies:
      - package: Sparkle
        product: Sparkle
